version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - ./static:/internal/static  
    command: uvicorn internal.main:app --host 0.0.0.0 --reload
